In [1]:
import pandas as pd
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score, precision_score, f1_score
from datetime import datetime

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', -1)

e:\anaconda3\envs\DeepLearning\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  This is separate from the ipykernel package so we can avoid doing imports until


In [3]:
# Caricamento del Training Set
training_set = pd.read_csv("../../datasets/training_set.csv")

In [4]:
training_set

comment_text  toxic
0      cocksucker before you piss around on my work                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1    
1      hey what is it talk what is it an exclusive group of some wp talibans who are good at destroying purist who gang up any one who asks them questions abt their and destructive non at wp ask sityush to clean up his behavior than issue me nonsensical warnings                                                                                                                                                                                                                                                                                                                             1    
2      bye dont look come or think of comming back tosser                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1    
3      you are gay or antisemmitian archangel white tiger meow greetingshhh uh there are two ways why you do erased my comment about that holocaust was brutally slaying of jews and not if you are than shave your head bald and go to the skinhead meetings if you doubt words of the bible that homosexuality is a deadly sin make a pentagram tatoo on your forehead go to the satanistic masses with your gay pals first and last warning you fucking gay i wont appreciate if any more nazi shwain would write in my page i dont wish to talk to you anymore beware of the dark side         1    
4      fuck your filthy mother in the ass dry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1    
...                                       ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ..    
30572  chris i dont know who you are talking to but it better aint be me because you are messing with the wrong guy better watch it or something bad will happen to you and let me tell ya im not kidding                                                                                                                                                                                                                                                                             

# GUARDA DOPO

In [5]:
# Lemmatizzazione
nltk.download('wordnet')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to C:\Users\Riccardo De
[nltk_data]     Cesaris\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\Riccardo De
[nltk_data]     Cesaris\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [5]:
lemmatizer = WordNetLemmatizer()

In [6]:
lista = training_set["comment_text"].to_list()

In [7]:
lista

['cocksucker before you piss around on my work',
 'hey what is it talk what is it an exclusive group of some wp talibans who are good at destroying purist who gang up any one who asks them questions abt their and destructive non at wp ask sityush to clean up his behavior than issue me nonsensical warnings',
 'bye dont look come or think of comming back tosser',
 'you are gay or antisemmitian archangel white tiger meow greetingshhh uh there are two ways why you do erased my comment about that holocaust was brutally slaying of jews and not if you are than shave your head bald and go to the skinhead meetings if you doubt words of the bible that homosexuality is a deadly sin make a pentagram tatoo on your forehead go to the satanistic masses with your gay pals first and last warning you fucking gay i wont appreciate if any more nazi shwain would write in my page i dont wish to talk to you anymore beware of the dark side',
 'fuck your filthy mother in the ass dry',
 'im sorry im sorry i scr

In [8]:
comment_text = list()

In [12]:
from nltk.tag import pos_tag
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Riccardo De
[nltk_data]     Cesaris\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


True

In [15]:
for frase in lista:
    tokens = word_tokenize(frase)
    lemmatized_tokens = list()
    for token in tokens:
        pos = pos_tag([token])[0][1][0].lower() if wordnet.synsets(token) else 'n'
        try:
            lemmatized_token = lemmatizer.lemmatize(token, pos=pos)
            lemmatized_tokens.append(lemmatized_token)
        except KeyError:
            # Se il POS non è valido, usa 'n' come default per la lemmatizzazione
            lemmatized_tokens.append(token)

    new_frase = ' '.join(lemmatized_tokens)
    comment_text.append(new_frase)

KeyboardInterrupt: 

In [ ]:
training_set2 = training_set.copy()

In [ ]:
training_set2['comment_text'] = comment_text

In [ ]:
training_set2

comment_text  toxic
0      cocksucker before you piss around on my work                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1    
1      hey what is it talk what is it an exclusive group of some wp taliban who are good at destroying purist who gang up any one who asks them question abt their and destructive non at wp ask sityush to clean up his behavior than issue me nonsensical warning                                                                                                                                                                                                                                                                                                                         1    
2      bye dont look come or think of comming back tosser                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1    
3      you are gay or antisemmitian archangel white tiger meow greetingshhh uh there are two way why you do erased my comment about that holocaust wa brutally slaying of jew and not if you are than shave your head bald and go to the skinhead meeting if you doubt word of the bible that homosexuality is a deadly sin make a pentagram tatoo on your forehead go to the satanistic mass with your gay pal first and last warning you fucking gay i wont appreciate if any more nazi shwain would write in my page i dont wish to talk to you anymore beware of the dark side          1    
4      fuck your filthy mother in the as dry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1    
...                                      ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..    
30572  chris i dont know who you are talking to but it better aint be me because you are messing with the wrong guy better watch it or something bad will happen to you and let me tell ya im not kidding                                                                                                                                                                                                                                                                                                                       

In [ ]:
import numpy as np

In [ ]:
i = np.random.randint(0, len(training_set))
print(training_set.iloc[i])
print(training_set2.iloc[i])

comment_text    the following things need to be retained a fuller quotation of horowitz that conveys his charges and stated implications to dees in fairness and to accomodate npov a balancing fuller quotation of berlet would also be needed reference to the allegations by arabia against berlets style of argument critique for guilt by association and critique for squashing free speech specification of how the dispute actually concluded not simply see here for example it should be noted that splc stood by berlet and berlet responded plus horowitzs counterresponse the fairest way of doing this is again to give both berlet and horowitz a representative quote in their own words
toxic           0                                                                                                                                                                                                                                                                                                              

# VETTORIZZAZZIONE

In [9]:
# Creazione Vettori TFIDF
vectorizer = TfidfVectorizer()

In [10]:
comment_text = training_set['comment_text']
type(comment_text)

pandas.core.series.Series

In [11]:
X_train = vectorizer.fit_transform(comment_text)

In [12]:
X_train.shape

(30577, 56091)

In [13]:
y_train = training_set['toxic']

In [14]:
y_train

0        1
1        1
2        1
3        1
4        1
        ..
30572    0
30573    0
30574    0
30575    0
30576    0
Name: toxic, Length: 30577, dtype: int64

In [15]:
rf_classifier = RandomForestClassifier()

In [16]:
rf_classifier.fit(X=X_train, y=y_train)

RandomForestClassifier()

In [17]:
rf_classifier.n_classes_

2

In [18]:
y_pred = rf_classifier.predict(X_train)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
print(accuracy_score(y_true=y_train, y_pred=y_pred))

0.9999345913595186


In [21]:
probs = rf_classifier.predict_proba(X_train)

In [22]:
probs[0]

array([0.07, 0.93])

In [25]:
probs[13888]

array([0., 1.])

In [26]:
probs[226]

array([0.11, 0.89])

In [27]:
probs[30575]

array([0.89, 0.11])